// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDecision } from "./ApprovalDecision";

export type ApprovalReplyParams = { 
/**
 * The `id` from the `approval.request` this answers.
 */
id: string, decision: ApprovalDecision, 
/**
 * The user's words when the decision carries one.
 */
reason: string | null, };
