// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user decided about an `approval.request`.
 */
export type ApprovalDecision = "allow" | "deny" | "deny_with_reason" | "allow_always";
