// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { streaming: boolean, approvals: boolean, sessions: boolean, diffs: boolean, context_usage: boolean, cost: boolean, };
