// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalReplyParams } from "./ApprovalReplyParams";
import type { InitializeParams } from "./InitializeParams";
import type { SessionLoadParams } from "./SessionLoadParams";
import type { ShutdownParams } from "./ShutdownParams";
import type { TurnStartParams } from "./TurnStartParams";

/**
 * A request from the shell to the engine. Adjacently tagged: `{"method":..,"params":..}`.
 */
export type ClientRequest = { "method": "initialize", "params": InitializeParams } | { "method": "shutdown", "params": ShutdownParams } | { "method": "session.load", "params": SessionLoadParams } | { "method": "turn.start", "params": TurnStartParams } | { "method": "approval.reply", "params": ApprovalReplyParams };
