// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FinalParams = { verdict: string | null, 
/**
 * Present only when the run failed. A run that succeeded never carries an empty error.
 */
error: string | null, };
