// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";

export type InitializeResult = { protocol_version: number, engine_version: string, capabilities: Capabilities, };
