// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";

export type InitializeParams = { 
/**
 * The protocol the shell speaks. The engine refuses a mismatch rather than guessing.
 */
protocol_version: number, client: ClientInfo, };
