// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalRequestParams } from "./ApprovalRequestParams";
import type { BranchCreatedParams } from "./BranchCreatedParams";
import type { ContextUsageParams } from "./ContextUsageParams";
import type { CostUpdateParams } from "./CostUpdateParams";
import type { FinalParams } from "./FinalParams";
import type { JsonRpc } from "./JsonRpc";
import type { NoticeParams } from "./NoticeParams";
import type { PlanUpdateParams } from "./PlanUpdateParams";
import type { RefParams } from "./RefParams";
import type { SessionReadyParams } from "./SessionReadyParams";
import type { StageDoneParams } from "./StageDoneParams";
import type { StageFailedParams } from "./StageFailedParams";
import type { StageStartParams } from "./StageStartParams";
import type { StageTokenParams } from "./StageTokenParams";
import type { ToolCallParams } from "./ToolCallParams";
import type { ToolDiffParams } from "./ToolDiffParams";
import type { ToolProgressParams } from "./ToolProgressParams";
import type { ToolResultParams } from "./ToolResultParams";
import type { TraceId } from "./TraceId";
import type { TurnDeltaParams } from "./TurnDeltaParams";
import type { TurnEndParams } from "./TurnEndParams";
import type { TurnStartedParams } from "./TurnStartedParams";
import type { VerdictReadyParams } from "./VerdictReadyParams";

/**
 * A message the engine pushes without being asked. One line, one JSON object.
 */
export type NotificationFrame = { jsonrpc: JsonRpc, trace_id: TraceId, } & ({ "method": "session.ready", "params": SessionReadyParams } | { "method": "turn.started", "params": TurnStartedParams } | { "method": "turn.delta", "params": TurnDeltaParams } | { "method": "turn.end", "params": TurnEndParams } | { "method": "stage.start", "params": StageStartParams } | { "method": "stage.token", "params": StageTokenParams } | { "method": "stage.done", "params": StageDoneParams } | { "method": "stage.failed", "params": StageFailedParams } | { "method": "tool.call", "params": ToolCallParams } | { "method": "tool.progress", "params": ToolProgressParams } | { "method": "tool.result", "params": ToolResultParams } | { "method": "tool.diff", "params": ToolDiffParams } | { "method": "approval.request", "params": ApprovalRequestParams } | { "method": "plan.update", "params": PlanUpdateParams } | { "method": "notice", "params": NoticeParams } | { "method": "diff.ready", "params": RefParams } | { "method": "verdict.ready", "params": VerdictReadyParams } | { "method": "branch.created", "params": BranchCreatedParams } | { "method": "context.usage", "params": ContextUsageParams } | { "method": "cost.update", "params": CostUpdateParams } | { "method": "final", "params": FinalParams });
