// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItem } from "./PlanItem";

export type PlanUpdateParams = { items: Array<PlanItem>, };
