// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a verdict came from a stage that could see the code or from the stage that wrote it.
 * The footer and the stage row both show this, because it changes how much a verdict is worth.
 */
export type Provenance = "independent" | "self_verification";
