// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pointer to something the engine produced on disk.
 */
export type RefParams = { 
/**
 * `ref` is a Rust keyword, so the field is `ref_` and serialises as `ref`.
 */
ref: string, };
