// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionLoadResult = { session_id: string, 
/**
 * What the session already knows. Empty on a fresh session; the shell says so plainly.
 */
resumed_messages: number, project_path: string, branch: string | null, };
