// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type SessionReadyParams = { session_id: string, project_path: string, model: string, permission_mode: PermissionMode, branch: string | null, 
/**
 * Ahead/behind counts. Absent when git has not reported them; the footer then shows no arrow
 * rather than a fabricated one.
 */
ahead: number | null, behind: number | null, resumed_messages: number, };
