// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity carried by a failure. The shell maps this to the error colour and never to anything
 * else.
 */
export type Severity = "info" | "warning" | "error";
