// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provenance } from "./Provenance";
import type { StageRole } from "./StageRole";

export type StageDoneParams = { stage_id: string, role: StageRole, summary: string, tokens_in: number, tokens_out: number, cost_usd: number, latency_ms: number, retry_count: number, artifact_ref: string | null, provenance: Provenance, };
