// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageRole } from "./StageRole";

export type StageTokenParams = { stage_id: string, role: StageRole, 
/**
 * A provider-supplied summary only. Raw private chain-of-thought is never sent.
 */
text: string, };
