// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolCallParams = { tool_id: string, name: string, 
/**
 * Pre-rendered, single-line arguments. The shell does not parse tool arguments.
 */
args: string, };
