// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type TurnStartParams = { prompt: string, 
/**
 * Permission posture for this turn. The engine never assumes one the shell did not send.
 */
permission_mode: PermissionMode, };
