package session

import (
	"fmt"
	"html"
	"os"
	"strings"
	"time"

	"github.com/RavaniRoshan/niki/internal/protocol"
)

// ExportToMarkdown generates a clean GitHub-Flavored Markdown transcript of the session.
func ExportToMarkdown(sessionID protocol.SessionId, store *Store) (string, error) {
	evts, err := store.Events(sessionID)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "# NikiCode Session Transcript: %s\n\n", sessionID)
	fmt.Fprintf(&sb, "*Exported on: %s*\n\n---\n\n", time.Now().Format(time.RFC1123))

	for _, e := range evts {
		switch e.Type {
		case protocol.EventTurnStarted:
			fmt.Fprintf(&sb, "### 👤 User\n\n%s\n\n", e.Text)
		case protocol.EventAssistantTextDelta:
			sb.WriteString(e.Text)
		case protocol.EventAssistantMessageDone:
			sb.WriteString("\n\n")
		case protocol.EventToolStarted:
			fmt.Fprintf(&sb, "<details><summary>🛠️ <b>Tool Call: %s</b></summary>\n\n", e.ToolName)
		case protocol.EventToolCompleted:
			fmt.Fprintf(&sb, "\n\n```\n%s\n```\n</details>\n\n", e.Text)
		case protocol.EventToolFailed:
			fmt.Fprintf(&sb, "\n\n❌ **Error**: %s\n</details>\n\n", e.Error)
		}
	}

	return sb.String(), nil
}

// ExportToHTML generates a standalone, self-contained dark-mode HTML transcript of the session.
func ExportToHTML(sessionID protocol.SessionId, store *Store) (string, error) {
	evts, err := store.Events(sessionID)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NikiCode Session ` + html.EscapeString(string(sessionID)) + `</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 2rem; line-height: 1.6; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { color: #38bdf8; border-bottom: 1px solid #334155; padding-bottom: 0.5rem; font-size: 1.5rem; }
  .user-msg { background: #1e293b; border-left: 4px solid #38bdf8; padding: 1rem; border-radius: 4px; margin: 1.5rem 0; font-weight: 500; }
  .assistant-msg { margin: 1.5rem 0; line-height: 1.7; color: #e2e8f0; }
  details { background: #1e293b; border: 1px solid #334155; border-radius: 4px; padding: 0.5rem 1rem; margin: 1rem 0; }
  summary { cursor: pointer; color: #94a3b8; font-family: monospace; font-size: 0.9rem; }
  pre { background: #090d16; padding: 1rem; border-radius: 4px; overflow-x: auto; color: #38bdf8; font-size: 0.85rem; }
  .badge { display: inline-block; padding: 0.2rem 0.5rem; font-size: 0.75rem; background: #334155; color: #94a3b8; border-radius: 3px; }
  .footer { margin-top: 3rem; border-top: 1px solid #334155; padding-top: 1rem; color: #64748b; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
<h1>NikiCode Session ` + html.EscapeString(string(sessionID)) + `</h1>
<div class="badge">Exported: ` + html.EscapeString(time.Now().Format("2006-01-02 15:04:05")) + `</div>
<hr style="border-color: #334155; margin: 1rem 0;">
`)

	for _, e := range evts {
		switch e.Type {
		case protocol.EventTurnStarted:
			fmt.Fprintf(&sb, "<div class=\"user-msg\">❯ %s</div>\n", html.EscapeString(e.Text))
		case protocol.EventAssistantTextDelta:
			sb.WriteString(html.EscapeString(e.Text))
		case protocol.EventAssistantMessageDone:
			sb.WriteString("\n<br/>\n")
		case protocol.EventToolStarted:
			fmt.Fprintf(&sb, "<details><summary>🛠️ Tool: %s</summary><pre>", html.EscapeString(e.ToolName))
		case protocol.EventToolCompleted:
			sb.WriteString(html.EscapeString(e.Text) + "</pre></details>\n")
		case protocol.EventToolFailed:
			fmt.Fprintf(&sb, "<span style=\"color:#f87171;\">Error: %s</span></pre></details>\n", html.EscapeString(e.Error))
		}
	}

	sb.WriteString(`
<div class="footer">Generated by NikiCode · Personal Coding-Agent Harness</div>
</div>
</body>
</html>`)

	return sb.String(), nil
}

// WriteExportToFile writes the exported session transcript to a specified destination file.
func WriteExportToFile(sessionID protocol.SessionId, format string, store *Store, outPath string) error {
	var content string
	var err error
	if strings.ToLower(format) == "html" {
		content, err = ExportToHTML(sessionID, store)
	} else {
		content, err = ExportToMarkdown(sessionID, store)
	}
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(content), 0o644)
}
