#!/usr/bin/env python3
"""Regenerate the per-test overrides in .config/nextest.toml from
.config/test-binary-groups — the single source of truth.

    ./scripts/gen-nextest-groups.py           rewrite the managed block
    ./scripts/gen-nextest-groups.py --check   exit 1 if the file is stale

Everything outside the BEGIN/END markers is hand-written and left alone.
tests/test_groups.py mirrors these checks in Rust, so a hand-edit that drifts
fails `cargo test` as well as this script.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GROUPS_FILE = ROOT / ".config" / "test-binary-groups"
NEXTEST_TOML = ROOT / ".config" / "nextest.toml"

BEGIN = "# BEGIN generated by scripts/gen-nextest-groups.py — edit .config/test-binary-groups instead"
END = "# END generated by scripts/gen-nextest-groups.py"

# Order matters only for readability of the generated file.
GROUP_ORDER = ["heavy", "heap"]


def parse_groups(path: Path) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {g: [] for g in GROUP_ORDER}
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise SystemExit(f"{path}:{lineno}: expected '<group> <binary>', got {raw!r}")
        group, binary = parts
        if group not in groups:
            raise SystemExit(f"{path}:{lineno}: unknown group {group!r} (known: {', '.join(GROUP_ORDER)})")
        if binary in groups[group]:
            raise SystemExit(f"{path}:{lineno}: {binary!r} listed twice in group {group!r}")
        groups[group].append(binary)
    dupes = {b for g in GROUP_ORDER for b in groups[g]}
    seen: set[str] = set()
    for g in GROUP_ORDER:
        for b in groups[g]:
            if b in seen:
                raise SystemExit(f"{path}: {b!r} is in more than one group")
            seen.add(b)

    for group, binaries in groups.items():
        for binary in binaries:
            if not (ROOT / "tests" / f"{binary}.rs").exists():
                raise SystemExit(f"{path}: {binary!r} is listed as {group} but tests/{binary}.rs does not exist")
    return groups


def render(groups: dict[str, list[str]]) -> str:
    out = [
        BEGIN,
        "# Source: .config/test-binary-groups. Regenerate with scripts/gen-nextest-groups.py.",
        "# These groups are the only thing stopping a 7.5 GiB host from OOMing:",
        "# the heavy and heap binaries run one at a time, everything else parallelises.",
        "",
    ]
    for group in GROUP_ORDER:
        binaries = groups[group]
        if not binaries:
            continue
        # `binary(name)` accepts a glob, but explicit names are deliberate: a
        # renamed test binary then fails loudly (no such file) instead of
        # silently matching nothing and quietly emptying the group again.
        filt = " | ".join(f"binary({b})" for b in binaries)
        out += ["[[profile.default.overrides]]", f"filter = '{filt}'", f"test-group = '{group}'", ""]
    out.append(END)
    return "\n".join(out)


def main() -> int:
    groups = parse_groups(GROUPS_FILE)
    block = render(groups)
    current = NEXTEST_TOML.read_text()

    if "--check" in sys.argv:
        stripped = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            block,
            current,
            flags=re.S,
        )
        if stripped == current:
            print("nextest.toml overrides are up to date")
            return 0
        print("nextest.toml overrides are STALE — run ./scripts/gen-nextest-groups.py", file=sys.stderr)
        return 1

    if BEGIN in current:
        updated = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, current, flags=re.S)
        action = "rewrote"
    else:
        updated = current.rstrip("\n") + "\n\n" + block + "\n"
        action = "appended"

    if updated == current:
        print("nextest.toml overrides already up to date")
        return 0
    NEXTEST_TOML.write_text(updated)
    print(f"{action} managed block in {NEXTEST_TOML.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
